### ISSUE TITLE
please specify license

### ISSUE THREAD

**Issue by ColinTalbert** [Winand/dataframemodel#1]
Thanks for creating this.  

No license is specified in the repository which makes reuse problematic.  Please specify a license if you intend others to use this code.

**Comment by Winand** [comment]
well... should i use BSD if the project uses BSD licenced [HierarchicalHeaderView](https://www.linux-apps.com/p/1132194/) ported to Python?

P. S. also it's still unusable with large amount of data. Too slow.

**Comment by ColinTalbert** [comment]
I'm no licensing expert but BSD would work great for my purposes.

Thanks,
Colin

Colin Talbert
Data Manager, Analyst and Developer
US Geological Survey, Fort Collins Science Center
2150 Centre Ave. Bldg. C
Fort Collins, CO 80526
(970) 226-9425

Work schedule:
Monday                     - 7:00 - 5:00
Tuesday - Friday      -  7:00 - 3:00

**Comment by Winand** [comment]
i've added MIT license to README file

**Comment by ColinTalbert** [comment]
Thank you for the license, and thank you for your work.

--Colin

Colin Talbert
Data Manager, Analyst and Developer
US Geological Survey, Fort Collins Science Center
2150 Centre Ave. Bldg. C
Fort Collins, CO 80526
(970) 226-9425

Work schedule:
Monday                     - 7:00 - 5:00
Tuesday - Friday      -  7:00 - 3:00
